In [1]:
import numpy as np

In [2]:
np.random.randint(12)

10

In [3]:
arr1=np.random.randn(12)

In [4]:
arr1

array([-1.61327892,  0.27970519, -0.73111272, -0.47851906, -0.46547286,
        1.62376494,  2.13061279,  0.06733175, -0.97477604, -2.21305013,
        0.08042497, -0.68771451])

In [5]:
np.sqrt(arr1)

<ipython-input-5-31bdbbe4b4c3>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr1)


array([       nan, 0.52887162,        nan,        nan,        nan,
       1.27427036, 1.45966188, 0.25948363,        nan,        nan,
       0.28359297,        nan])

In [6]:
np.exp(arr1)

array([0.19923327, 1.3227398 , 0.48137306, 0.61970045, 0.62783815,
       5.07215075, 8.42002496, 1.06965028, 0.37727684, 0.10936656,
       1.08374753, 0.50272373])

In [7]:
arr2=np.random.randn(12)

In [8]:
arr2

array([ 0.21917492, -1.64275732, -0.37259136,  1.02032592,  1.66972677,
        0.31550764,  1.34403866,  0.89613279,  0.38101343,  2.01942356,
        0.06004596, -2.17894058])

In [9]:
np.add(arr1,arr2)

array([-1.39410401, -1.36305213, -1.10370408,  0.54180686,  1.20425391,
        1.93927258,  3.47465145,  0.96346454, -0.59376261, -0.19362657,
        0.14047093, -2.86665509])

In [10]:
np.minimum(arr1,arr2)

array([-1.61327892, -1.64275732, -0.73111272, -0.47851906, -0.46547286,
        0.31550764,  1.34403866,  0.06733175, -0.97477604, -2.21305013,
        0.06004596, -2.17894058])

In [11]:
np.maximum(arr1,arr2)

array([ 0.21917492,  0.27970519, -0.37259136,  1.02032592,  1.66972677,
        1.62376494,  2.13061279,  0.89613279,  0.38101343,  2.01942356,
        0.08042497, -0.68771451])