In [1]:
import numpy as np


In [2]:
b=np.random.random((3,3))

In [3]:
c=np.random.random((3,3))

In [4]:
b

array([[0.23088086, 0.68971664, 0.70312743],
       [0.46092872, 0.43625222, 0.2658459 ],
       [0.75189394, 0.25018617, 0.44239616]])

In [5]:
c

array([[0.2111269 , 0.60883503, 0.99352634],
       [0.90628381, 0.99405679, 0.48019376],
       [0.15418972, 0.91104893, 0.28558921]])

In [6]:
b + c

array([[0.44200776, 1.29855167, 1.69665377],
       [1.36721253, 1.43030901, 0.74603966],
       [0.90608365, 1.1612351 , 0.72798537]])

In [7]:
b -c

array([[ 0.01975395,  0.08088161, -0.29039892],
       [-0.44535509, -0.55780456, -0.21434786],
       [ 0.59770422, -0.66086276,  0.15680695]])

In [8]:
b*c

array([[0.04874516, 0.41992365, 0.69857562],
       [0.41773224, 0.43365948, 0.12765754],
       [0.11593431, 0.22793184, 0.12634357]])

In [9]:
b/c

array([[1.09356436, 1.13284652, 0.70770889],
       [0.50859203, 0.43886047, 0.55362215],
       [4.87642082, 0.27461332, 1.54906469]])

In [10]:
b%c

array([[0.01975395, 0.08088161, 0.70312743],
       [0.46092872, 0.43625222, 0.2658459 ],
       [0.13513508, 0.25018617, 0.15680695]])

In [11]:
1/c

array([[4.73648781, 1.64248105, 1.00651584],
       [1.10340711, 1.00597875, 2.0824927 ],
       [6.48551687, 1.09763588, 3.50153286]])

In [12]:
2/b

array([[8.66247658, 2.89974154, 2.84443462],
       [4.33906569, 4.58450385, 7.52315525],
       [2.65994963, 7.99404697, 4.52083492]])

In [13]:
b += c #b=b+c

In [14]:
b

array([[0.44200776, 1.29855167, 1.69665377],
       [1.36721253, 1.43030901, 0.74603966],
       [0.90608365, 1.1612351 , 0.72798537]])

In [15]:
 b**2

array([[0.19537086, 1.68623644, 2.87863402],
       [1.86927011, 2.04578386, 0.55657518],
       [0.82098759, 1.34846696, 0.52996269]])

In [16]:
0.52522541 *0.52522541

0.2758617313096681

In [17]:
1.45346678 * 1.45346678

2.1125656805635686