In [1]:
import numpy as np


In [2]:
arr=np.random.randn(4,4)

In [3]:
arr

array([[-0.48186505,  0.25220935, -0.22270894, -0.73734441],
       [-1.0998941 , -0.84088334,  0.41576658, -0.17907496],
       [-0.66146183,  1.11979908,  0.40478363, -0.96466218],
       [-1.57632884, -0.81174992, -0.14156912, -0.77357709]])

In [4]:
arr.sum()

-6.298561130476822

In [5]:
arr.mean()

-0.39366007065480135

In [6]:
arr.var()

0.44246797266583715

In [7]:
arr.std()

0.665182661128383

In [8]:
np.where(arr<0)


(array([0, 0, 0, 1, 1, 1, 2, 2, 3, 3, 3, 3]),
 array([0, 2, 3, 0, 1, 3, 0, 3, 0, 1, 2, 3]))

In [9]:
np.where(arr<0,0,arr)

array([[0.        , 0.25220935, 0.        , 0.        ],
       [0.        , 0.        , 0.41576658, 0.        ],
       [0.        , 1.11979908, 0.40478363, 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [10]:
arr.sort()

In [11]:
arr

array([[-0.73734441, -0.48186505, -0.22270894,  0.25220935],
       [-1.0998941 , -0.84088334, -0.17907496,  0.41576658],
       [-0.96466218, -0.66146183,  0.40478363,  1.11979908],
       [-1.57632884, -0.81174992, -0.77357709, -0.14156912]])